/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedNumber: typeof import('./src/components/animated-number.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    MetaballBackground: typeof import('./src/components/metaball-background.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleGaugeChart: typeof import('./src/components/single-gauge-chart.vue')['default']
  }
}
