/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedNumber: typeof import('./src/components/animated-number.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonIcon: typeof import('@ionic/vue')['IonIcon']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonInputPasswordToggle: typeof import('@ionic/vue')['IonInputPasswordToggle']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSpinner: typeof import('@ionic/vue')['IonSpinner']
    IonTabBar: typeof import('@ionic/vue')['IonTabBar']
    IonTabButton: typeof import('@ionic/vue')['IonTabButton']
    IonTabs: typeof import('@ionic/vue')['IonTabs']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    MetaballBackground: typeof import('./src/components/metaball-background.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleGaugeChart: typeof import('./src/components/single-gauge-chart.vue')['default']
  }
}
